name: 'run-smoketests-action'
description: 'Runs smoketests on the provided environment'
inputs: 
  engine_version:
    required: true
    description: 'RAI engine version'
 
  environment:
   required: true
   description: 'Environment name'
  
  CLIENT_ID:
   required: true
   description: 'Client ID'
   
runs:
  using: "composite"
  steps:
  - run: |
      echo "${{ github.event.inputs.engine_version }}"
      echo "${{ github.event.inputs.environment }}"
      echo "${{ github.event.inputs.CLIENT_ID }}"
      echo "VAL=${{secrets.CLIENT_ID_STAGING}}" >> $GITHUB_ENV
    shell: bash
  - run: echo ${{env.VAL}}
    shell: bash
