name: 'Test Always Step'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: 'Fail the workflow'
      id: check-step
      run: |
        echo "WORKFLOW_CONCLUSION=failure" >> $GITHUB_ENV
        exit 1
        echo "WORKFLOW_CONCLUSION=completed" >> $GITHUB_ENV
      shell: bash
      
    - name: Failure 
      if: always()
      uses: julia-actions/setup-julia@v1
      with:
        version: 1.8.1
          
      
