name: 'Test Always Step'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: 'Fail the workflow'
      id: check-step
      run: |
        echo "WORKFLOW_CONCLUSION=failure" >> $GITHUB_ENV
      shell: bash
      
    - run: echo 'failed'
      shell: bash
      if: |
        env.WORKFLOW_CONCLUSION == 'failure' 
    
    - run: echo 'completed'
      shell: bash
      if: |
        env.WORKFLOW_CONCLUSION == 'completed' 
      
      
