name: "Close stale Releases"
on:
  schedule:
    - cron: "*/1 * * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - name: cleanup-release-candidates
        run: |
          print('Hello World ....')
        shell: python
