name: "Close stale Releases"
on:
  workflow_dispatch:
  #schedule:
  #- cron: "*/5 * * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - name: install-github-api
        run: pip install PyGithub   
      - name: cleanup-release-candidates
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          from github import Github
          import os
          import sys
          from pprint import pprint
          import requests
          import json
          import copy
          import os
          import subprocess
          import requests
          
          gh = Github(os.getenv('GITHUB_TOKEN'))
          
          #org = gh.get_organization("irfanazam1")
          #repo = org.get_repo("githubactions")
          for repo in gh.get_user().get_repos():
            print(repo.name)
          #repo = gh.get_user().get_repo('githubactions')  
          #releases = repo.get_releases()
          #print(release[0].tag_name())
            
        shell: python
