name: "Close stale Releases"
on:
  schedule:
  - cron: "*/5 * * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - name: cleanup-release-candidates
        run: |
          from github import Github
          import os
          import sys
          from pprint import pprint
          import requests
          import json
          import copy
          import os
          import subprocess
          import requests
          
          gh = Github(os.getenv('GITHUB_TOKEN'))
          
          org = g.get_organization("RelationalAI")
          repo = org.get_repo("raicode")
          
          releases = repo.get_releases()
          print(release[0].tag_name()
            
        shell: python
