name: test

on:
  push:
    branches:
      - main
      
jobs:    
  one:
    runs-on: ubuntu-latest
    name: one
    steps:
    - name: Checkout code
    - uses: actions/checkout@v2
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.sha }}
        release_name: ${{ github.sha }}
        body: ''
        draft: false
        prerelease: false
