name: deploy

on:
 workflow_dispatch:
   inputs:
     sha:
       description: 'sha'
       required: true
       default: ''   
     
     engine_version:
      description: 'engine version'
      required: false
      default: ''
jobs:    
  build:
    runs-on: ubuntu-latest
    name: build
    steps:
     - name: build-code
       run: echo "Buiding Code"
     - uses: ./.github/actions/test.yml
       with:
         engine_version: 'xyzabcd'
         environment: 'latest'
        
  staging:
    needs: build
    name: deploy-staging
    environment:
      name: staging
    runs-on: ubuntu-latest
    steps:
     - name: deploy-staging
       run: echo "Deploying to staging ...."
  
  production:
    needs: staging
    name: deploy-production
    environment:
      name: production
    runs-on: ubuntu-latest
    steps:
     - name: deploy-production
       run: echo "Deploying to production ...."
