name: dual_test.yml

on:
 workflow_dispatch:
   inputs:
     sha:
       description: 'sha'
       required: true
       default: ''
    
jobs:    
  dual-test:
    name: dual test
    uses: ./.github/workflows/dual.yml
    with:
      environment: ${{ github.event.inputs.sha }}
    secrets: inherit
     
