name: dual_test.yml

on:
 workflow_dispatch:
   inputs:
     sha:
       description: 'sha'
       required: true
       default: ''
    
jobs:    
  dual-test:
    runs-on: ubuntu-latest
    name: Dual Test
    steps:
     - uses: actions/checkout@v3
     - uses: ./.github/workflows/dual.yml
       with:
        sha: ${{ github.sha }}
     
