name: dual.yml

on:
  workflow_call:
   inputs:
     sha:
       type: string
       description: 'sha'
       required: true
       default: ''
 
  workflow_dispatch:
   inputs:
     sha:
       description: 'sha'
       required: true
       default: ''
    
jobs:    
  one:
    runs-on: ubuntu-latest
    name: Job One
    steps:
    - run: |
        sleep 30
        echo ${{ github.event.inputs.sha }}
      shell: bash
