name: on-commit-main

on:
  push:
    branches: main
     
jobs:    
  build:
    runs-on: ubuntu-latest
    name: on-commit-main
    steps:
      - run: |
         curl \
         -H "Accept: application/vnd.github+json" \ 
         -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.context.repo.owner }}/${{ github.context.repo.repo }}/issues/${{ github.context.sha }}/labels"
