name: on-commit-main

on:
  push:
    branches: main
     
jobs:    
  build:
    runs-on: ubuntu-latest
    name: on-commit-main
    steps:
      - name: Get PR labels
        id: pr-labels
        uses: joerick/pr-labels-action@v1.0.6
      - run: |
          echo "${{ steps.pr-labels.outputs.labels }}"
