name: on-pr

on:
  push:
    branches:
      - main
     
jobs:    
 get_pr_labels_job:
    runs-on: ubuntu-latest
    name: A job to get the PR labels
    steps:
    - name: Get PR labels action step
      id: get_pr_labels
      uses: irfanazam1/get-pr-labels-on-push-action@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: See result
      run: echo "${{ steps.get_pr_labels.outputs.result }}"
    
    - uses: actions/setup-python@v4.3.0
      with:
        python-version: 3.10.0
        
    - run: |
        export SHA="${{ github.sha }}"
        export GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}"
        id = `python ./.github/scripts/get_check_run_id.py`
        echo id
