name: smoke-tests-precheck

on:
 - status
 
jobs:     
  smoke-tests-precheck:
    runs-on: ubuntu-latest
    name: Smoke Tests Pre-check
    if: ${{ github.event.state }} == 'success'
    steps:
     - name: set-branch
       id: set-branch
       run: |
        echo ::set-output name=branch::${{toJSON(github.event.bracnhes)}}
     - name: get-branch
       run: |
        echo $branch | jq '.name'
       env:
        branch = ${{ steps.set-branch.outputs.branch}}
     - name: check-build-completion
       id: expression
       run: echo ::set-output name=regex::".*:binary.linux:.*"
     - uses: actions-ecosystem/action-regex-match@v2
       id: regex-match
       with:
         text: ${{ github.event.context }}
         regex: ${{ steps.expression.outputs.regex }}
     - name: check-completion
       if: ${{ steps.regex-match.outputs.match != '' }}
       run: |
        curl --request POST --url "https://api.github.com/repos/irfanazam1/githubactions/actions/workflows/onstatus.yaml/dispatches" \
        --header "Authorization: token ${{ secrets.PAT }}" \
        --data "{ \"ref\": \"${{ env.branch }}\", \"inputs\":{ \"sha\": \"${{ github.event.sha }}\" }}"
        
