name: smoke-tests

on:
 - status

jobs:
  check-commit-status:
    runs-on: ubuntu-latest
    name: Check Commit Status
    if: ${{ github.event.state }} != 'success'
    steps:
    - name: Exit Workflow
      run: exit 0
       
  smoke-tests-precheck:
    runs-on: ubuntu-latest
    name: Smoke Tests Pre-check
    needs: check-commit-status
    # if: ${{ github.event.state }} == 'success'
    steps:
     - name: check-build-completion
       id: expression
       run: echo ::set-output name=regex::".*:binary.linux:.*"
     - uses: actions-ecosystem/action-regex-match@v2
       id: regex-match
       with:
         text: ${{ github.event.context }}
         regex: ${{ steps.expression.outputs.regex }}
     - name: check-completion
       if: ${{ steps.regex-match.outputs.match == '' }}
       run: exit 1    
               
  provision-compute:
    runs-on: ubuntu-latest
    name: Provision Compute
    needs: smoke-tests-precheck
    # if: ${{ github.event.state }} == 'success'
    steps:
     - name: provision_compute
       run: |
        curl --request POST --url "https://api.github.com/repos/irfanazam1/githubactions/statuses/${{ github.event.sha }}" \
        --header "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
        --header 'content-type: application/json' \
        --data '{"state": "pending", "description": "started provisioning compute", "context": "Provision Compute", "target_url": "http://link-in-status/"}'
     - uses: jakejarvis/wait-action@master
       with:
         time: '30s'
     - name: complete_provision_compute
       run: |
        curl --request POST --url "https://api.github.com/repos/irfanazam1/githubactions/statuses/${{ github.event.sha }}" \
        --header "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
        --header 'content-type: application/json' \
        --data '{"state": "success", "description": "compute successfully provisioned", "context": "Provision Compute", "target_url": "http://link-in-status/"}'
        
  smoke-tests:
    runs-on: ubuntu-latest
    name: Run Smoke Tests
    needs: provision-compute
    steps:
     - name: start_smoke_test
       run: |
        curl --request POST --url "https://api.github.com/repos/irfanazam1/githubactions/statuses/${{ github.event.sha }}" \
        --header "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
        --header 'content-type: application/json' \
        --data '{"state": "pending", "description": "smoke tests started", "context": "Smoke Tests", "target_url": "http://link-in-status/"}'
     - uses: jakejarvis/wait-action@master
       with:
         time: '30s'
     - name: complete_smoke_test
       run: |
        curl --request POST --url "https://api.github.com/repos/irfanazam1/githubactions/statuses/${{ github.event.sha }}" \
        --header "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
        --header 'content-type: application/json' \
        --data '{"state": "success", "description": "smoke tests completed successfully", "context": "Smoke Tests", "target_url": "http://link-in-status/"}'
        
  deprovision-compute:
    runs-on: ubuntu-latest
    name: De-provision Compute
    needs: smoke-tests
    steps:
     - name: delete_compute
       run: |
        curl --request POST --url "https://api.github.com/repos/irfanazam1/githubactions/statuses/${{ github.event.sha }}" \
        --header "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
        --header 'content-type: application/json' \
        --data '{"state": "success", "description": "De-Provisioning Compyte", "context": "De-Provision Compute", "target_url": "http://link-in-status/"}'
