name: smoke-tests

on:
 workflow_dispatch:
   inputs:
     sha:
       description: 'sha'
       required: true
       default: ''
    
jobs:    
  provision-compute:
    runs-on: ubuntu-latest
    name: Provision Compute
    steps:
     - name: provision_compute
       run: |
        curl --request POST --url "https://api.github.com/repos/irfanazam1/githubactions/statuses/${{ github.event.inputs.sha }}" \
        --header "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
        --header 'content-type: application/json' \
        --data '{"state": "pending", "description": "started provisioning compute", "context": "Provision Compute", "target_url": "http://link-in-status/"}'
     - uses: jakejarvis/wait-action@master
       with:
         time: '10s'
     - name: complete_provision_compute
       run: |
        curl --request POST --url "https://api.github.com/repos/irfanazam1/githubactions/statuses/${{ github.event.inputs.sha}}" \
        --header "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
        --header 'content-type: application/json' \
        --data '{"state": "success", "description": "compute successfully provisioned", "context": "Provision Compute", "target_url": "http://link-in-status/"}'
        
  smoke-tests:
    runs-on: ubuntu-latest
    name: Run Smoke Tests
    needs: provision-compute
    steps:
     - name: start_smoke_test
       run: |
        curl --request POST --url "https://api.github.com/repos/irfanazam1/githubactions/statuses/${{ github.event.inputs.sha }}" \
        --header "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
        --header 'content-type: application/json' \
        --data '{"state": "pending", "description": "smoke tests started", "context": "Smoke Tests", "target_url": "http://link-in-status/"}'
     - uses: jakejarvis/wait-action@master
       with:
         time: '10s'
     - name: complete_smoke_test
       run: |
        curl --request POST --url "https://api.github.com/repos/irfanazam1/githubactions/statuses/${{ github.event.inputs.sha }}" \
        --header "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
        --header 'content-type: application/json' \
        --data '{"state": "success", "description": "smoke tests completed successfully", "context": "Smoke Tests", "target_url": "http://link-in-status/"}'
        
        curl --request POST --url "https://api.github.com/repos/irfanazam1/githubactions/check-runs" \
        --header "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
        --header 'content-type: application/json' \
        --data '{"name": "smoke-tests", "head_sha": "${{ github.event.inputs.sha }}", "conclusion": "completed", "details_url": "https://google.coom"}'
        
  deprovision-compute:
    runs-on: ubuntu-latest
    name: De-provision Compute
    needs: smoke-tests
    steps:
     - name: delete_compute
       run: |
        curl --request POST --url "https://api.github.com/repos/irfanazam1/githubactions/statuses/${{github.event.inputs.sha}}" \
        --header "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
        --header 'content-type: application/json' \
        --data '{"state": "success", "description": "De-Provisioning Compyte", "context": "De-Provision Compute", "target_url": "http://link-in-status/"}'
