name: smoke-tests-precheck

on:
 - status
 
jobs:
  smoke-tests-precheck:
    if: ${{ github.event.state == 'success' }}
    runs-on: ubuntu-latest
    name: Smoke Tests Pre-check
    steps:
     - name: check-build-completion
       id: expression
       run: echo ::set-output name=regex::".*:binary.linux:.*"
     - uses: actions-ecosystem/action-regex-match@v2
       id: regex-match
       with:
         text: ${{ github.event.context }}
         regex: ${{ steps.expression.outputs.regex }}
     - name: check-completion
       if: ${{ steps.regex-match.outputs.match != '' }}
       run: |
        curl --request POST --url "https://api.github.com/repos/irfanazam1/githubactions/actions/workflows/onstatus.yaml/dispatches" \
        --header "Authorization: token ${{ secrets.PAT }}" \
        --data "{ \"ref\": \"${{ github.event.branches[0].name }}\", \"inputs\":{ \"sha\": \"${{ github.event.sha }}\" }}"
        
