name: smoke-tests-precheck

on:
 - status
 
jobs:     
  smoke-tests-precheck:
    runs-on: ubuntu-latest
    name: Smoke Tests Pre-check
    if: ${{ github.event.state }} == 'success'
    steps:
     - name: check-build-completion
       id: expression
       run: echo ::set-output name=regex::".*:binary.linux:.*"
     - uses: actions-ecosystem/action-regex-match@v2
       id: regex-match
       with:
         text: ${{ github.event.context }}
         regex: ${{ steps.expression.outputs.regex }}
     - name: check-completion
       if: ${{ steps.regex-match.outputs.match != '' }}
       run: |
        curl --request POST --url "https://api.github.com/repos/irfanazam1/githubactions/workflows/smoke-tests/dispatches" \
        --header "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
        --header 'content-type: application/json' \
        --data '{"ref": "main", "description": "starting smoke tests", "context": "${{ github.event.context }}", \
        "target_url": "http://link-in-status/", "inputs": {"input1":"value1","input2":"value2"}}'
        
