name: deploy-provisioner

on:
 - status

jobs:
  deploy-provisioner:
    runs-on: ubuntu-latest
    name: Deploy Provisioner
    if: ${{ github.event.state }} == 'success'
    steps:
     - name: calc_regex
       id: vars
       run: echo ::set-output name=regex::".*:binary.linux:.*"
     - uses: actions-ecosystem/action-regex-match@v2
       id: regex-match
       with:
         text: ${{ github.event.context }}
         regex: ${{ steps.vars.outputs.regex }}
     - uses: wei/curl@v1
       if: ${{ steps.regex-match.outputs.match != '' }}
       with:
          args: -request POST --url "https://api.github.com/repos/irfanazam1/githubactions/statuses/${GITHUB_SHA}" \
          --header "Authorization: token ${secrets.GITHUB_TOKEN}" \
          --header 'content-type: application/json' \
          --data '{\"state\": \"success\", \"description\":\"my status 123\", \"context\":\"anything:ia-test:binary.linux:anything\", \"target_url\":\"http://link-in-status/\"}'
