name: smoke-tests

on:
 workflow_dispatch:
   inputs:
     sha:
       description: 'sha'
       required: true
       default: ''
     environment:
       description: 'environment name'
       required: true
       default: 'LATEST'   
    
jobs:    
  provision-compute:
    runs-on: ubuntu-latest
    name: Prepare Config
    steps:
     - name: prepare_latest_config
       if: ${{ github.event.inputs.environment == 'latest'  }}
       run: |
        mkdir -p $HOME/.rai
        echo -e "[latest]\n"
        echo -e "access_key=123\n"
        echo -e "${{ secrets.PASSWORD_${{ github.event.inputs.environment }} }}"
     - name: prepare_staging_config
       if: ${{ github.event.inputs.environment == 'staging'  }}
       run: |
        mkdir -p $HOME/.rai
        echo -e "[staging]\n"
        echo -e "${{ secrets.PASSWORD_${{ github.event.inputs.environment }} }}"
        
