name: test

on:
 workflow_dispatch:
   
jobs:    
  build:
    runs-on: ubuntu-latest
    name: build
    steps:
      - name: build-label-check
        if: ${{ github.event.labels.build != '' }}
        run: echo "Build label is present"
