name: test

on:
 workflow_dispatch:
   
jobs:    
  build:
    runs-on: ubuntu-latest
    name: build
    steps:
     - run: |
         sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
         sudo chmod a+x /usr/local/bin/yq
         yq --help
        
     
     - uses: cachix/install-nix-action@v15
     - run: |
         nix-env -iA nixpkgs.yq w -i '.provisioner.raiserver.version = strenv(ENGINE_VERSION)' relationalai-infra/infra/charts/raicloud/values.yaml
     
