name: test

on:
 workflow_dispatch:
   
jobs:    
  one:
    runs-on: ubuntu-latest
    name: one
    steps:
      - uses: convictional/trigger-workflow-and-wait@v1.3.0
        with:
          owner: irfanazam1
          repo: githubactions
          github_token: ${{ secrets.PAT }}
          workflow_file_name: one.yml
          wait_interval: 300
          inputs: '{"sha":"123456"}'
          propagate_failure: true
          trigger_workflow: true
          wait_workflow: true
  
  two:
    runs-on: ubuntu-latest
    name: two
    steps:
      - uses: convictional/trigger-workflow-and-wait@v1.3.0
        with:
          owner: irfanazam1
          repo: githubactions
          github_token: ${{ secrets.PAT }}
          workflow_file_name: two.yml
          wait_interval: 300
          inputs: '{"sha":"123456"}'
          propagate_failure: true
          trigger_workflow: true
          wait_workflow: true
 
  three:
    runs-on: ubuntu-latest
    name: three
    steps:
      - uses: convictional/trigger-workflow-and-wait@v1.3.0
        with:
          owner: irfanazam1
          repo: githubactions
          github_token: ${{ secrets.PAT }}
          workflow_file_name: three.yml
          wait_interval: 30
          inputs: '{"sha":"123456"}'
          propagate_failure: true
          trigger_workflow: true
          wait_workflow: true  
      
  finally:
    runs-on: ubuntu-latest
    name: Finalize Status
    needs:
     - one
     - two
     - three
    if: always()
    steps:
    - uses: technote-space/workflow-conclusion-action@v2
    - run: |
        curl --fail --request POST --url "https://api.github.com/repos/irfanazam1/githubactions/check-runs" \
        --header "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
        --header 'content-type: application/json' \
        --data '{"name": "RAICloud Benchmark", "conclusion": "${{ env.WORKFLOW_CONCLUSION }}", "details_url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"}'
