name: Test re-run

on:
  workflow_dispatch:

jobs:
  SuccessfulJob:
    runs-on: ubuntu-latest
    name: Successful Job
    strategy:
      fail-fast: false
    steps:
      - run: echo 'Successful job'

  FailedJob:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    name: Failed Job
    steps:
      - run: | 
          echo 'Failed job'
          exit 1
  
  Finalize-Result:
    name: Finalize Results
    needs:
      - SuccessfulJob
      - FailedJob
    runs-on: ubuntu-latest
    if: always()
    steps:
    - uses: technote-space/workflow-conclusion-action@v3
    - name: check-re-run
      if: ${{ env.WORKFLOW_CONCLUSION == 'failure' }}
      run: |
        failed_jobs_ids=`curl -s -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{secrets.GITHUB_TOKEN }}" https://api.github.com/repos/irfanazam1/githubactions/actions/runs/${{ github.run_id }}/jobs | jq -r '.jobs[] | select(.conclusion | contains("failure")).id'`
        for id in "${jobs[@]}"
        do
          curl -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{secrets.GITHUB_TOKEN }}" https://api.github.com/repos/irfanazam1/githubactions/actions/jobs/$id/rerun   
        done
