name: test

on:
 workflow_dispatch:
   
jobs:    
  build:
    runs-on: ubuntu-latest
    name: build
    steps:
      # Checkout smoke tests
      - uses: actions/checkout@v2
        with:
          ref: main
          repository: irfanazam1/githubactions
          path: githubactions
     
      - run: |
          cd githubactions
          echo "" >> README.md
          git config --global user.email "mazam76@gmail.com"
          git config --global user.name "Irfan Azam"
          git add README.md
          git commit -m "updated the readme.md"
          git push
          echo "COMMIT_ID=$(git rev-parse HEAD)" >> $GITHUB_ENV
        
      - uses: actions/checkout@v2
        with:
          ref: deploy/raicloud/prod
          repository: irfanazam1/githubactions
          path: githubactions
       
      - run: |
          cd githubactions
          git cherry-pick ${{ env.COMMIT_ID }}
          git push
