name: test

on:
 workflow_dispatch:
   
jobs:    
  build:
    runs-on: ubuntu-latest
    name: build
    steps:
      - name: build-label-check
      - uses: actions/checkout@v2
        with:
          ref: main
          repository: irfanazam1/githubactions
          path: githubactions
