name: test

on:
 workflow_dispatch:
   
jobs:    
  one:
    runs-on: ubuntu-latest
    name: one
    steps:
      # Checkout smoke tests
      - run: |
         sleep 30
        shell: bash
  
  two:
    runs-on: ubuntu-latest
    name: two
    steps:
      # Checkout smoke tests
      - run: |
         sleep 50
        shell: bash
 
  three:
    runs-on: ubuntu-latest
    name: three
    steps:
      # Checkout smoke tests
      - run: |
         sleep 40
         exit 1
        shell: bash
        
      
  finally:
    runs-on: ubuntu-latest
    name: Finalize Status
    needs:
     - one
     - two
     - three
    if: always()
    steps:
    - uses: technote-space/workflow-conclusion-action@v2
    - run: echo ${{ env.WORKFLOW_CONCLUSION }}
