name: test

on:
 workflow_dispatch:
   
jobs:    
  build:
    runs-on: ubuntu-latest
    name: build
    steps:
      # Checkout smoke tests
      - uses: actions/checkout@v2
        with:
          ref: main
          repository: irfanazam1/githubactions
          path: githubactions
     
      - run: |
          git checkout deploy/raicloud/prod
          git status
       
          
